#!/data/data/com.termux/files/usr/bin/bash
clear
unset LD_PRELOAD
dir=$HOME/DangerV1
if  [ $dir != $HOME/DangerV1 ]
	then
		dir=$HOME/DangerV1
	fi
keluar="Yakin Mau Keluar?"
return="Ketik Enter Untuk Kembali Kemenu"
#DIRECTORY="/data/data/com.termux/files/usr/share/figlet"
TMP="DangerV1 By : InYourHeart"
VERSION="v1.1"
#colors
cyan='\033[1;36m'
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
blue='\033[1;34m'
purple='\033[1;35m'
reset='\033[0m'
#if [ ! -d "$DIRECTORY" ]; then
#apt update && apt upgrade
#fi
echo -e "$red________  ________  ________   ________  _______   ________  ___      ___  _____     
|\   ___ \|\   __  \|\   ___  \|\   ____\|\  ___ \ |\   __  \|\  \    /  /|/ __  \    
\ \  \_|\ \ \  \|\  \ \  \\ \  \ \  \___|\ \   __/|\ \  \|\  \ \  \  /  / |\/_|\  \   
 \ \  \ \\ \ \   __  \ \  \\ \  \ \  \  __\ \  \_|/_\ \   _  _\ \  \/  / /\|/ \ \  \"  
echo -e "$green  \ \  \_\\ \ \  \ \  \ \  \\ \  \ \  \|\  \ \  \_|\ \ \  \\  \\ \    / /      \ \  \ 
   \ \_______\ \__\ \__\ \__\\ \__\ \_______\ \_______\ \__\\ _\\ \__/ /        \ \__\
    \|_______|\|__|\|__|\|__| \|__|\|_______|\|_______|\|__|\|__|\|__|/          \|__|"
echo
